version: '{build}'
clone_folder: c:\build\text
pull_requests:
  do_not_increment_build_number: true
configuration: Debug
branches:
  except:
    - /^(?i:continuous)$/
skip_tags: true
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      QT_PROFILE: msvc2015
      QTDIR: C:\Qt\5.10.1\msvc2015
      CMAKE_GENERATOR: "Visual Studio 14 2015"
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      QT_PROFILE: msvc2017_64
#      QTDIR: C:\Qt\5.10.1\msvc2017_64
#      CMAKE_GENERATOR: "Visual Studio 15 2017"
# FIXME: WinRT builds are disabled due to linker issues
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      QT_PROFILE: winrt_x86_msvc2017
#      QTDIR: C:\Qt\5.10.1\winrt_x86_msvc2017
#      CMAKE_GENERATOR: "Visual Studio 15 2017"
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      QT_PROFILE: winrt_x64_msvc2017
#      QTDIR: C:\Qt\5.10.1\winrt_x64_msvc2017
#      CMAKE_GENERATOR: "Visual Studio 15 2017"
init:
  - set PATH=%QTDIR%\bin;%PATH%
  - cmake --version
build_script:
  - git clone -b develop git://github.com/lirios/fluid.git
  - cd fluid
  - git submodule update --init --recursive
  - cd ..
  - mkdir build
  - cd build
  - cmake -DLIRI_LOCAL_ECM:BOOL=ON .. -G "%CMAKE_GENERATOR%"
  - cmake --build .
notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    channel: '#events'
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
